MyBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^login/', views.login),
    url(r'^logout/', views.logout),
    url(r'^register/', views.register),
    url(r'^myEditBack/(?P<usersite>\w+)', views.myEditBack),
    url(r'^del_article/', views.delArticle),
    url(r'^addArticle/', views.addArticle),
    url(r'^index/', views.index),
    url(r'^valid_code/', views.valid_code),
    url(r'^blog/', include('app01.urls')),

    url(r'^$', views.index),
]

app01/urls.py
from django.conf.urls import url
from app01 import views

urlpatterns = [
    url("articleUpDown/$", views.articleUpDown),
    url("commentUpDown/$", views.commentUpDown),
    url("comment/$", views.comment),
    url("(?P<user_site>\w+)/$", views.showTime),
    url("(?P<user_site>\w+)/article/(?P<article_id>\d+)", views.articleDetail),
    url("(?P<user_site>\w+)/article2/(?P<article_id>\d+)", views.articleDetail2),
    url("(?P<user_site>\w+)/article/(?P<classify>category|tag)/(?P<para>\w+)", views.showTime),
    url("(?P<user_site>\w+)/article/(?P<classify>date)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)", views.showTime),
    url("article/(?P<classify>category|tag)/(?P<para>\w+)", views.index),
    url("article/(?P<classify>date)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)", views.index),
]

app01/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# __author__ = "DaChao"
# Date: 2017/9/6

from django import forms
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError


class RegForm(forms.Form):

    username = forms.CharField(min_length=1,
                               max_length=11,
                               widget=forms.TextInput(attrs={"class": "text username", "placeholder": "请输入账号"}),
                               error_messages={'required': '用户名不能为空'})
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "text password", "placeholder": "请输入密码"}),
                               error_messages={'required': '密码不能为空'})
    re_password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "text re_password", "placeholder": "请再次输入密码"}),
                                  error_messages={'required': '密码不能为空'})
    mail = forms.EmailField(widget=forms.EmailInput(attrs={"class": "text mail", "placeholder": "请输入邮箱"}),
                            error_messages={'required': '邮箱不能为空', 'invalid': '邮箱格式错误'})
    valid_code = forms.CharField(widget=forms.EmailInput(attrs={"class": "text valid_code", "placeholder": "请输入验证码", "style": "color: #FFFFFF !important; position:absolute; z-index:100;", }),
                                 error_messages={'required': '验证码不能为空'})

    def __init__(self, request, *args, **kwargs):
        # forms.Form.__init__(self, *args, **kwargs)  # 继承父辈的方法一
        super(RegForm, self).__init__(*args, **kwargs)  # 继承父辈的方法二
        self.request = request

    def clean_username(self):
        if self.cleaned_data["username"].isdigit() or self.cleaned_data["username"].isalpha():
            raise ValidationError("用户名必须包含数字和字符！")
        else:
            return self.cleaned_data["username"]

    def clean_password(self):
        if len(self.cleaned_data["password"]) < 2:
            raise ValidationError("密码必须大于1位！")
        else:
            return self.cleaned_data["password"]

    def clean_valid_code(self):
        if self.cleaned_data["valid_code"].upper() == self.request.session["valid_code"].upper():
            return self.cleaned_data["valid_code"]
        else:
            raise ValidationError("验证码错误！")

    def clean(self):
        '''
        全局钩子，
        注意：password在局部钩子未通过后，为无,直接字典取值，会报错
        :return:
        '''
        if self.cleaned_data.get("password") != self.cleaned_data.get("re_password"):
            raise ValidationError("密码必须一致！")
        else:
            return self.cleaned_data

templates/addArticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加文章</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/bootstrap/homeSite.css">
    <script src="/static/js/jquery-3.2.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <script src="/static/kindeditor-4.1.10/kindeditor-all.js"></script>

</head>
<body>


<div class="container">


    <form action="/addArticle/" method="post">
         {% csrf_token %}
         <h3>标题</h3>
        <input type="text" name="title">
        <h3>content</h3>

        <textarea name="article_content" id="article_content" cols="30" rows="10"></textarea>


        <p><input type="submit"></p>
    </form>


    <script>

        KindEditor.create("#article_content",{
            width:"200px",
            height:"400px",
            resizeType:0,

            uploadJson:"/upload_file/",
            extraFileUploadParams:{
                "csrfmiddlewaretoken":"{{ csrf_token }}"
            }

        })

    </script>
</div>


</body>
</html>

templates/articleDetail.html
{% extends "base.html" %}


{% block content %}

    <h2 class="blog-post-title">{{ article_obj.name }}</h2>
    <p class="blog-post-meta">{{ article_obj.create_time|date:"Y-m-d h:i" }}&nbsp;by <a
            href="#">{{ article_obj.blog.user.username }}</a></p>
    <p>{{ article_obj.articledetail.content }}</p>
    <div><a href="javascript:;" class="article_up">
        <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;赞
        <span class="article_up_count">{{ article_obj.up_count }}</span>&nbsp;
        <span class="article_up_red"></span>
    </a>&nbsp;&nbsp;&nbsp;
        <a href="javascript:;">
            <span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;踩
            <span>{{ article_obj.down_count }}</span>
        </a>&nbsp;&nbsp;&nbsp;
        <a href="#comment">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论
            <span>{{ article_obj.comment_count }}</span>
        </a>
    </div>

    <hr>

    <h4>已有评论：</h4>
    <ul class="list-group comment_list">
        {% for comment in comment_obj %}

            <li class="list-group-item comment_item" comment_id={{ comment.nid }}>
                <span>#</span><span class="comment_number">{{ forloop.counter }}</span>
                <a href="javascript:;">{{ comment.user.username }}</a>
                <span>{{ comment.create_time|date:"Y-m-d H:i" }}</span>
                <div>
                    {% if comment.parent_id %}
                        <span>
                            <a href="javascript:;">@</a>{{ comment.parent_id.user.username }}:{{ comment.parent_id.content }}
                        </span>
                        <p>{{ comment.content }}</p>
                    {% else %}
                        {{ comment.content }}
                    {% endif %}
                </div>
                <a href="#comment" class="comment_pd">
                    <span class="glyphicon glyphicon-comment"></span>&nbsp;回复
                </a>
                <a href="javascript:;" class="comment_pd comment_down">
                    <span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;踩
                    <span>{{ comment.down_count }}</span>
                </a>&nbsp;&nbsp;&nbsp;
                <a href="javascript:;" class="comment_pd comment_up">
                    <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;赞
                    <span class="comment_up_count">{{ comment.up_count }}</span>&nbsp;
                    <span class="comment_up_red"></span>
                </a>
            </li>

        {% endfor %}
    </ul>

    <hr>

    <h4><span class="glyphicon glyphicon-comment"></span>&nbsp;{{ request.user.username }}&nbsp;发表评论：</h4>

    <!--评论框-->
    <div>
        <textarea name="comment" id="comment" cols="66" rows="6"></textarea>
        <a href="javascript:;" class="submit_comment"> <input type="button" value="提交评论"></a>
    </div>

    <script>

        // 字符串模块化
        String.prototype.format = function () {
            var args = arguments;
            return this.replace(/\{(\d+)\}/g, function (s, i) {
                return args[i];
            });
        };


        var article_id = {{ article_obj.nid }};
        var parent_comment_id = "";
        var father_comment_username = "";

        $(function () {
            // 文章点赞（踩)
            $(".article_up").click(function () {

                {% if request.user.is_authenticated %}
                    $.ajax({
                        url: "/blog/articleUpDown/",
                        type: "POST",
                        data: {
                            "article_id": article_id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },
                        success: function (data) {
                            data = JSON.parse(data)
                            if (data["flag"]) {
                                $(".article_up_count").text(parseInt($(".article_up_count").text()) + 1)
                            }
                            else {
                                $(".article_up").children(".article_up_red").text("已点赞").css("color", "red");
                                setTimeout(function () {
                                    $(".article_up").children(".article_up_red").text("")
                                }, 1000)
                            }

                        }
                    })
                {% else %}
                    location.href = "/blog/{{ request.path }}"; // 当前页url
                    {#                    console.log("{{ request.path }}");#}

                {% endif %}

            })

            // 评论点赞
            $(".comment_up").click(function () {
                var $this = $(this);
                {% if request.user.is_authenticated %}
                    var comment_id = $(this).parent().attr("comment_id");
                    $.ajax({
                        url: "/blog/commentUpDown/",
                        type: "POST",
                        data: {
                            "comment_id": comment_id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },
                        success: function (data) {
                            data = JSON.parse(data);
                            if (data["flag"]) {
                                console.log($this.children(".comment_up_count").text());

                                $this.children(".comment_up_count").text(parseInt($this.children(".comment_up_count").text()) + 1);
                            }
                            else {
                                $this.children(".comment_up_red").text("已点赞").css("color", "red");
                                setTimeout(function () {
                                    $this.children(".comment_up_red").text("")
                                }, 1000)
                            }

                        }
                    })
                {% else %}
                    location.href = "/blog/{{ request.path }}"; // 当前页url

                {% endif %}

            })

            // 回复评论之评论事件
            $(".comment_list").on("click", ".comment_pd", function () {
                parent_comment_id = $(this).parent().attr("comment_id");
                father_comment_username = $(this).siblings().eq(2).text();
                $("#comment").val("@" + father_comment_username + "\n")
            })


            // 评论
            $(".submit_comment").click(function () {
                var index = $("#comment").val().indexOf("\n");
                var content = $("#comment").val().substr(index + 1);  // 默认的是起始位置

                {% if request.user.is_authenticated %}
                    $.ajax({
                        url: "/blog/comment/",
                        type: "POST",
                        data: {
                            "article_id": article_id,
                            "content": content,
                            "parent_comment_id": parent_comment_id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },

                        success: function (data) {
                            var temp = father_comment_username;
                            if (temp) {
                                father_comment_username = "<a>@</a>" + temp
                            }
                            data = JSON.parse(data);

                            s = '<li class="list-group-item comment_item" comment_id={0}>' +
                                '<span>#</span><span>{1}</span>&nbsp;<a href="javascript:;">{2}</a>&nbsp;' +
                                '<span>{3}</span><div><span>{4}</span><p>{5}</p></div><a href="#comment" class="comment_pd">' +
                                '<span class="glyphicon glyphicon-comment"></span>&nbsp;回复</a>' +
                                '<a href="javascript:;" class="comment_pd comment_down">' +
                                '<span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;踩<span>{6}</span></a>' +
                                '&nbsp;&nbsp;&nbsp;<a href="javascript:;" class="comment_pd comment_up">' +
                                '<span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;赞' +
                                '<span class="comment_up_count">{7}</span>&nbsp;<span class="comment_up_red"></span></a></li>';

                            s = s.format(
                                data["comment_id"],
                                '#',
                                '{{ request.user.username }}',
                                data["comment_createTime"],
                                father_comment_username,
                                content,
                                data["up_count"],
                                data["down_count"]
                            );

                            $(".comment_list").append(s);
                            $("#comment").val("");

                        }
                    })
                {% else %}
                    location.href = "/blog/{{ request.path }}"; // 当前页url

                {% endif %}
            })

        })


    </script>

{% endblock %}

templates/articleDetail2.html
{% extends "base.html" %}


{% block content %}

    <h2 class="blog-post-title">{{ article_obj.name }}</h2>
    <p class="blog-post-meta">{{ article_obj.create_time|date:"Y-m-d h:i" }}&nbsp;by <a
            href="#">{{ article_obj.blog.user.username }}</a></p>
    <p>{{ article_obj.articledetail.content }}</p>
    <div><a href="javascript:;" class="article_up">
        <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;赞
        <span class="article_up_count">{{ article_obj.up_count }}</span>&nbsp;
        <span class="article_up_red"></span>
    </a>&nbsp;&nbsp;&nbsp;
        <a href="javascript:;">
            <span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;踩
            <span>{{ article_obj.down_count }}</span>
        </a>&nbsp;&nbsp;&nbsp;
        <a href="#comment">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论
            <span>{{ article_obj.comment_count }}</span>
        </a>
    </div>

    <hr>

    <h4>已有评论：</h4>
    <div class="list-group comment_list">

    </div>

    <hr>

    <h4><span class="glyphicon glyphicon-comment"></span>&nbsp;{{ request.user.username }}&nbsp;发表评论：</h4>

    <!--评论框-->
    <div>
        <textarea name="comment" id="comment" cols="66" rows="6"></textarea>
        <a href="javascript:;" class="submit_comment"> <input type="button" value="提交评论"></a>
    </div>

    <script>

        // 字符串模块化
        String.prototype.format = function () {
            var args = arguments;
            return this.replace(/\{(\d+)\}/g, function (s, i) {
                return args[i];
            });
        };

        // 评论树
        function CommentTree(commentList) {

            var htmls = "";

            $.each(commentList, function (k, v) {
                var comment_str = '';
                {#                 var temp="<div class='content'><span>{0}</span></div>".format(v["nid"]);#}

                var temp = '<div class="list-group-item comment_item" comment_id={0} class="comment">' +
                    '<span>#</span><span>{1}</span>&nbsp;<a href="javascript:;">{2}</a>&nbsp;' +
                    '<span>{3}</span><div><p>{4}</p></div><a href="#comment" class="comment_pd">' +
                    '<span class="glyphicon glyphicon-comment"></span>&nbsp;回复</a>' +
                    '<a href="javascript:;" class="comment_pd comment_down">' +
                    '<span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;踩<span>{5}</span></a>' +
                    '&nbsp;&nbsp;&nbsp;<a href="javascript:;" class="comment_pd comment_up">' +
                    '<span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;赞' +
                    '<span class="comment_up_count">{6}</span>&nbsp;<span class="comment_up_red"></span></a>';

                temp = temp.format(
                    v["nid"],
                    v["id"],
                    v["user__nickname"],
                    v["create_time"],
                    v["content"],
                    v["down_count"],
                    v["up_count"]
                );

                comment_str += temp;

                if (v["children_comments"]) {
                    comment_str += CommentTree(v["children_comments"])
                }
                comment_str += "</div>";
                htmls += comment_str
            });

            return htmls
        }

        // 评论渲染
        $.ajax({
            url: "",
            type: "GET",
            success: function (data) {
                var MyCommentlist = JSON.parse(data);

                // 处理s
                console.log(MyCommentlist);
                s = CommentTree(MyCommentlist);
                console.log(s);

                $(".comment_list").append(s)
            }
        })


        var article_id = {{ article_obj.nid }};
        var parent_comment_id = "";
        var father_comment_username = "";

        $(function () {
            // 文章点赞（踩)
            $(".article_up").click(function () {

                {% if request.user.is_authenticated %}
                    $.ajax({
                        url: "/blog/articleUpDown/",
                        type: "POST",
                        data: {
                            "article_id": article_id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },
                        success: function (data) {
                            data = JSON.parse(data)
                            if (data["flag"]) {
                                $(".article_up_count").text(parseInt($(".article_up_count").text()) + 1)
                            }
                            else {
                                $(".article_up").children(".article_up_red").text("已点赞").css("color", "red");
                                setTimeout(function () {
                                    $(".article_up").children(".article_up_red").text("")
                                }, 1000)
                            }

                        }
                    })
                {% else %}
                    location.href = "/blog/{{ request.path }}"; // 当前页url
                    {#                    console.log("{{ request.path }}");#}

                {% endif %}

            })

            // 评论点赞

            $(".comment_list").on("click", ".comment_up", function () {
                var $this = $(this);
                {% if request.user.is_authenticated %}
                    var comment_id = $(this).parent().attr("comment_id");
                    $.ajax({
                        url: "/blog/commentUpDown/",
                        type: "POST",
                        data: {
                            "comment_id": comment_id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },
                        success: function (data) {
                            data = JSON.parse(data);
                            if (data["flag"]) {
                                console.log($this.children(".comment_up_count").text());

                                $this.children(".comment_up_count").text(parseInt($this.children(".comment_up_count").text()) + 1);
                            }
                            else {
                                $this.children(".comment_up_red").text("已点赞").css("color", "red");
                                setTimeout(function () {
                                    $this.children(".comment_up_red").text("")
                                }, 1000)
                            }

                        }
                    })
                {% else %}
                    location.href = "/blog/{{ request.path }}"; // 当前页url

                {% endif %}

            })

            // 回复评论之评论事件
            $(".comment_list").on("click", ".comment_pd", function () {
                parent_comment_id = $(this).parent().attr("comment_id");
                father_comment_username = $(this).siblings().eq(2).text();
                $("#comment").val("@" + father_comment_username + "\n")
            })

            // 评论
            $(".submit_comment").click(function () {
                var index = $("#comment").val().indexOf("\n");
                var content = $("#comment").val().substr(index + 1);  // 默认的是起始位置

                {% if request.user.is_authenticated %}
                    $.ajax({
                        url: "/blog/comment/",
                        type: "POST",
                        data: {
                            "article_id": article_id,
                            "content": content,
                            "parent_comment_id": parent_comment_id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },

                        success: function (data) {
                            var temp = father_comment_username;
                            if (temp) {
                                father_comment_username = "<a>@</a>" + temp
                            }
                            data = JSON.parse(data);

                            s = '<li class="list-group-item comment_item" comment_id={0}>' +
                                '<span>#</span><span>{1}</span>&nbsp;<a href="javascript:;">{2}</a>&nbsp;' +
                                '<span>{3}</span><div><span>{4}</span><p>{5}</p></div><a href="#comment" class="comment_pd">' +
                                '<span class="glyphicon glyphicon-comment"></span>&nbsp;回复</a>' +
                                '<a href="javascript:;" class="comment_pd comment_down">' +
                                '<span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;踩<span>{6}</span></a>' +
                                '&nbsp;&nbsp;&nbsp;<a href="javascript:;" class="comment_pd comment_up">' +
                                '<span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;赞' +
                                '<span class="comment_up_count">{7}</span>&nbsp;<span class="comment_up_red"></span></a></li>';

                            s = s.format(
                                data["comment_id"],
                                '#',
                                '{{ request.user.username }}',
                                data["comment_createTime"],
                                father_comment_username,
                                content,
                                data["up_count"],
                                data["down_count"]
                            );

                            $(".comment_list").append(s);
                            $("#comment").val("");

                        }
                    })
                {% else %}
                    location.href = "/blog/{{ request.path }}"; // 当前页url

                {% endif %}
            })

        })


    </script>

{% endblock %}

templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0067)http://www.17sucai.com/preview/668095/2017-07-19/perfect/index.html -->
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>欢迎注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'login/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/demo.css' %}">
    <!--必要样式-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/component.css' %}">
    <!--[if IE]>
<script src="js/html5.js"></script>
<![endif]-->
    <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
    .en-markup-crop-options {
        top: 18px !important;
        left: 50% !important;
        margin-left: -100px !important;
        width: 200px !important;
        border: 2px rgba(255, 255, 255, .38) solid !important;
        border-radius: 4px !important;
    }

    .en-markup-crop-options div div:first-of-type {
        margin-left: 0 !important;
    }

    input:-webkit-autofill {
        background-color: transparent;
    !important;
        background-image: none;
    !important;
        color: #000;
    !important;
    }

    </style>
</head>
<body>
<div class="container demo-1">
    <div class="content">
        <div id="large-header" class="large-header" style="height: 651px;">
            <canvas id="demo-canvas" width="1366" height="651"></canvas>
            <div class="logo_box">
                {#                <h3>^-^ Welcome To JOIN My World! ^-^</h3>#}
                <form action="/register/" name="f" id="ajaxform" method="post">
                    {% csrf_token %}
                    <span id="s1"></span>
                    <div class="input_outer">
                        <span class="u_user"></span>
                        {{ form_obj.username }}
                    </div>
                    <span id="s2"></span>
                    <div class="input_outer">
                        <span class="us_uer"></span>
                        {{ form_obj.password }}
                    </div>
                    <span id="s3"></span>
                    <div class="input_outer">
                        <span class="us_uer"></span>
                        {{ form_obj.re_password }}
                    </div>
                    <span id="s4"></span>
                    <div class="input_outer">
                        {{ form_obj.mail }}
                    </div>
                    <span id="s5"></span>
                    <div class="input_outer">
                        {{ form_obj.valid_code }}
                        <a href="javascript:;" class="refresh"><img src="/valid_code/" alt="" class="valid_img" style="float: right;margin-top: 7px"></a>
                    </div>
                    <span></span>
                    <div class="mb2"><a class="act-but submit" href="javascript:;" style="color: #FFFFFF">注册</a></div>
                </form>
            </div>
        </div>
    </div>
</div><!-- /container -->
<script src="{% static 'login/TweenLite.min.js' %}"></script>
<script src="{% static 'login/EasePack.min.js' %}"></script>
<script src="{% static 'login/rAF.js' %}"></script>
<script src="{% static 'login/demo-1.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.js' %}"></script>

<script>

    // 验证码刷新
    $(function () {
        $(".refresh").click(function () {
            $(".valid_img")[0].src += "?";
        })
    })

    // ajax注册验证
    $(function () {
        $(".submit").click(function () {

            for (var i=1;i<6;i++){
                $("#s"+i).text("")
            }

            var username = $("#id_username").val();
            var password = $("#id_password").val();
            var re_password = $("#id_re_password").val();
            var mail = $("#id_mail").val();
            var valid_code = $("#id_valid_code").val();
            var csrf = $("[name='csrfmiddlewaretoken']").val();

            var formData = new FormData();

            formData.append("username", username);
            formData.append("password", password);
            formData.append("re_password", re_password);
            formData.append("mail", mail);
            formData.append("valid_code", valid_code);
            formData.append("csrfmiddlewaretoken", csrf);

            $.ajax({
                url: "/register/",
                type: "POST",
                data: formData,
                processData: false,      // 使用formdata,processData,contentType必须设为false
                contentType: false,
                success: function (data) {
{#                    alert(123);#}
                    data = JSON.parse(data);
                    if (data["flag"]) {
                        location.href = "/"
                    }
                    else {
                        var errors_dict = data["errors"];
                        console.log(errors_dict);
                        for (var i in errors_dict) {
                            console.log(i);
                            console.log(errors_dict[i]);
                            $("#s2").text(errors_dict["__all__"]).css({"color": "red"})
                            $("#id_" + i).parent().prev().text(errors_dict[i]).css({"color": "red"});
                        }
                    }
                },
                error:function (data) {
                    alert(123)
                }
            })
        })
    })

</script>
</body>
</html>

templates/showContent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>


{{ content|safe }}

</body>
</html>